
services:
  db:
    image: postgres:16
    container_name: param_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB:        ${POSTGRES_DB}
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: param_app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

#  pgadmin:
#    image: dpage/pgadmin4:7
#    container_name: param_pgadmin
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "5050:80"
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  pgdata:
  pgadmin_data:
